name: Build helm chart

on:
  push:
    branches:
      - 'main'
    paths:
      - deploy/charts/**
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish the helm chart to ghcr.io'
        type: boolean
        default: false

jobs:
  build-chart:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - name: Build helm chart
        run: |
          helm repo add minio https://charts.min.io/
          helm dependency build deploy/charts/distr
          helm lint --strict deploy/charts/distr
          helm package deploy/charts/distr
      - name: Login to GitHub Container Registry (tag or manual only)
        if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.publish }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Distr Registry (tag or manual only)
        if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.publish }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: registry.distr.sh
          username: ${{ github.actor }}
          password: ${{ secrets.DISTR_TOKEN }}
      - name: Push helm chart to ghcr.io (tag or manual only)
        if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.publish }}
        run: |
          for chart in distr-*.tgz; do
              helm push "$chart" oci://ghcr.io/distr-sh/charts
              helm push "$chart" oci://registry.distr.sh/glasskube/charts
          done
