name: Build helm chart

on:
  push:
    branches:
      - 'main'
    paths:
      - deploy/charts/**
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish the helm chart to ghcr.io'
        type: boolean
        default: false

jobs:
  build-chart:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - name: Build helm chart
        run: |
          helm repo add minio https://charts.min.io/
          helm repo add dex https://charts.dexidp.io
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm dependency build deploy/charts/distr
          helm lint --strict deploy/charts/distr
          helm package deploy/charts/distr
      - name: Login to GitHub Container Registry (tag or manual only)
        if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.publish }}
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Distr Registry (tag or manual only)
        if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.publish }}
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: registry.distr.sh
          username: ${{ github.actor }}
          password: ${{ secrets.DISTR_TOKEN }}
      - name: Push helm chart to ghcr.io (tag or manual only)
        if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.publish }}
        run: |
          for chart in distr-*.tgz; do
              helm push "$chart" oci://ghcr.io/glasskube/charts
              helm push "$chart" oci://registry.distr.sh/glasskube/charts
          done
